### ISSUE TITLE
Lean Inception

### ISSUE THREAD

**Issue by mibasFerraz** [fga-eps-mds/2023.2-PCGO-DOC#5]
Realização da técnica de lean inception com a galera de MDS e EPS ajudando ativamente no desenvolvimento.

**Comment by julisous** [comment]
Preparação para iniciar o lean no dia 13/09:

1. Definição do escopo  da reunião 
2. Elaboração da agenda  
3. DryRun da apresentação 
4.Alinhamento com MDS
