### ISSUE TITLE
Dojo de Javascript

### ISSUE THREAD

**Issue by vitordiniz25** [fga-eps-mds/2023.2-PCGO-DOC#7]
Realizar um dojo completo acerca dos javascript com a participação ativa com o grupo de MDS.

Instrutores: Vitor e Natanael
Horário: 15/09 20:00

**Comment by vitordiniz25** [comment]
Atualizando o horário do treinamento para sábado 16/09.

Instrutores: Vitor e Natanael
Horário: 16/09 09:00

**Comment by vitordiniz25** [comment]
O dojo foi realizado no sábado 16/09.

Link da gravação: https://unbbr-my.sharepoint.com/:v:/g/personal/180132385_aluno_unb_br/EWlzLDj14AJCjgZc4d560cgBNekXNakuSNrti8Q7OXCWZQ

Repositório com código-fonte: https://github.com/vitordiniz25/dojo-js

**Comment by fernandes-natanael** [comment]
Segue também repositório com uma representação mais real no uso do Typescript/Javascript em um projeto de api do backend usando o framework Nest.js+MongoDB como base de dados

https://github.com/fernandes-natanael/dojo-javascript-exemplo-projeto
